name: Showcase Update

on:
  schedule:    
    - cron:  '5 8 * * 0'
  workflow_dispatch:
    inputs:
      name:
        description: 'Update Showcase'
        default: 'Update'
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:  
    - name: 'Update Showcase'
      run: make update
    - name: 'Commit Changes'
      uses: stefanzweifel/git-auto-commit-action@v4
